"""create documents chunks financial_metrics

Revision ID: 177f956bcb81
Revises: 
Create Date: 2026-10-03 12:14:51.431526

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177f956bcb81'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_key', sa.String(length=64), nullable=False, comment='如 600519_2024_annual'),
    sa.Column('company_code', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=False, comment='annual | h1 | q1 | q3'),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('index_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=16), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'parsing', 'chunking', 'embedding', 'ready', 'failed')", name='ck_documents_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_key')
    )
    op.create_index(op.f('ix_documents_company_code'), 'documents', ['company_code'], unique=False)
    op.create_index('ix_documents_company_year', 'documents', ['company_code', 'report_year'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_report_year'), 'documents', ['report_year'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chunk_uid', sa.String(length=128), nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_uid', sa.String(length=128), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='0=父块 1=子块'),
    sa.Column('chunk_type', sa.String(length=16), nullable=False, comment='text | table'),
    sa.Column('heading_path', sa.String(length=512), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=True, comment='元|万元|亿元'),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=True, comment='FY2024|H1-2024'),
    sa.Column('statement_type', sa.String(length=16), nullable=True, comment='balance|income|cashflow|other'),
    sa.Column('table_flags', postgresql.ARRAY(sa.String(length=24)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("chunk_type IN ('text', 'table')", name='ck_chunks_type'),
    sa.CheckConstraint('level IN (0, 1)', name='ck_chunks_level'),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_uid')
    )
    op.create_index(op.f('ix_chunks_doc_id'), 'chunks', ['doc_id'], unique=False)
    op.create_index('ix_chunks_doc_strategy', 'chunks', ['doc_id', 'strategy'], unique=False)
    op.create_index(op.f('ix_chunks_parent_uid'), 'chunks', ['parent_uid'], unique=False)
    op.create_index(op.f('ix_chunks_strategy'), 'chunks', ['strategy'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False, comment='FY | H1 | Q1 | Q3'),
    sa.Column('metric_code', sa.String(length=48), nullable=False, comment='revenue | net_profit | ...'),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=False, comment='归一后单位'),
    sa.Column('raw_unit', sa.String(length=8), nullable=True, comment='抽取时原始单位'),
    sa.Column('source_doc_id', sa.BigInteger(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_chunk_uid', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verify_status', sa.String(length=16), nullable=False, comment='unverified | cross_checked | mismatch | manual_ok'),
    sa.Column('verify_source', sa.String(length=32), nullable=True, comment='如 akshare'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verify_status IN ('unverified', 'cross_checked', 'mismatch', 'manual_ok')", name='ck_metric_verify_status'),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'report_year', 'period', 'metric_code', name='uq_metric_identity')
    )
    op.create_index(op.f('ix_financial_metrics_company_code'), 'financial_metrics', ['company_code'], unique=False)
    op.create_index('ix_metrics_lookup', 'financial_metrics', ['company_code', 'report_year', 'metric_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_lookup', table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_company_code'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_chunks_strategy'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_parent_uid'), table_name='chunks')
    op.drop_index('ix_chunks_doc_strategy', table_name='chunks')
    op.drop_index(op.f('ix_chunks_doc_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_report_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index('ix_documents_company_year', table_name='documents')
    op.drop_index(op.f('ix_documents_company_code'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
